### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by MeganHoooo** [Luffy03/VoCo#1]

**Comment by Luffy03** [comment]
Hello, many thanks for your attention to our work! 
The code will be available as soon as possible (possibly this month). We are checking the codes and the checkpoints. Since we want to release our 10k-pretrained codes, it may take a few more days. Sorry for that.

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
