### ISSUE TITLE
dataset merging

### ISSUE THREAD

**Issue by PANHAOC** [Luffy03/VoCo#11]
Hello, multiple datasets were used for training in the paper. After reading the get_loader code, it was found that these datasets were finally concatenated into a large list. I want to know why the labels of the dataset do not need to be unified, for example, for the same organ (lung) in two datasets, its ground truth ID may not be the same. Isn't it confusing to train with a portion of data ID 10 representing the lungs and a portion of ID 8 representing the lungs?

**Comment by Luffy03** [comment]
Many thanks for your attention to our work!
Our work is designed for self-supervised learning, thus we don't have labels.
I am a little confused with your problem, why the two lung datasets (ID 8 and 9) cannot be merged?

**Comment by PANHAOC** [comment]
Thank you very much for your reply. For multi label semantic segmentation, to merge the two datasets meaning that we should identify all lungs in this dataset and change their corresponding GT IDs to specific values. Similarly, similar standardized operations are also required for the stomach, kidneys, and other organs.This job is a lot of work for me. I think it is difficult to normalize hundreds or thousands of samples in the dataset, so I am confused about the dataset merging.

**Comment by Luffy03** [comment]
Do you want to change the label IDs? Seems not a big problem. Although it is not related to our work, I can write a preliminary function for you as follows:
![image](https://github.com/Luffy03/VoCo/assets/52514670/4063fa2b-fa29-4855-9193-dfbe131582ac)
You can refer to the MONAI documents for details https://docs.monai.io/en/stable/.

**Comment by PANHAOC** [comment]
I see, thank you very much for your reply
