### ISSUE TITLE
About the downstream tasks

### ISSUE THREAD

**Issue by kare305** [Luffy03/VoCo#12]
Hello, congratulations on completing the exciting work! Regarding pre training weights, I would like to know if it is possible to provide weights for downstream tasks related to the CC-CCII dataset classification task?

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work!
No problem about sharing the pre-trained checkpoints, I will release it after double-checking. By the way, have you downloaded the CC-CCII dataset? Do I need to share it?

**Comment by kare305** [comment]
Thank you very much, I have downloaded the CC-CCII dataset. Looking forward to your sharing of pre-trained weights.

**Comment by Luffy03** [comment]
Dear kare, recently we found that the simplest 3d-unet is better than swin-unetr in the cc-ccii dataset. If you are only interested in this dataset instead of pre-training, I suggest that 3d-unet is a better choice for cc-ccii. I provide the pre-trained checkpoints and logs here (https://www.dropbox.com/scl/fo/okgg7unv4iazhi13wj1lp/AG8FVkQmnN9svvIaZUVvA9I?rlkey=angfy2wh3q8wtscgbf8pmmhp9&st=aq94torh&dl=0).
If you prefer swin-unetr, I will soon release it too.

**Comment by kare305** [comment]
> Dear kare, recently we found that the simplest 3d-unet is better than swin-unetr in the cc-ccii dataset. If you are only interested in this dataset instead of pre-training, I suggest that 3d-unet is a better choice for cc-ccii. I provide the pre-trained checkpoints and logs here (https://www.dropbox.com/scl/fo/okgg7unv4iazhi13wj1lp/AG8FVkQmnN9svvIaZUVvA9I?rlkey=angfy2wh3q8wtscgbf8pmmhp9&st=aq94torh&dl=0). If you prefer swin-unetr, I will soon release it too.

Wow, your response speed is surprising. Thank you for your valuable advice. I am not actually interested in CC-CCII, but I want to pre train a model on a publicly available large-scale dataset and then fine tune it on my own classification task dataset. If using 3d-unet, do we need to train additional linear layers during fine-tuning?

**Comment by kare305** [comment]
> Dear kare, recently we found that the simplest 3d-unet is better than swin-unetr in the cc-ccii dataset. If you are only interested in this dataset instead of pre-training, I suggest that 3d-unet is a better choice for cc-ccii. I provide the pre-trained checkpoints and logs here (https://www.dropbox.com/scl/fo/okgg7unv4iazhi13wj1lp/AG8FVkQmnN9svvIaZUVvA9I?rlkey=angfy2wh3q8wtscgbf8pmmhp9&st=aq94torh&dl=0). If you prefer swin-unetr, I will soon release it too.

Wow, your response speed is surprising. Thank you for your valuable advice. I am not actually interested in CC-CCII, but I want to pre train a model on a publicly available large-scale dataset and then fine tune it on my own classification task dataset. I will try the weights and models you provided first. Thank you again for your reply.

**Comment by kare305** [comment]
> Dear kare, recently we found that the simplest 3d-unet is better than swin-unetr in the cc-ccii dataset. If you are only interested in this dataset instead of pre-training, I suggest that 3d-unet is a better choice for cc-ccii. I provide the pre-trained checkpoints and logs here (https://www.dropbox.com/scl/fo/okgg7unv4iazhi13wj1lp/AG8FVkQmnN9svvIaZUVvA9I?rlkey=angfy2wh3q8wtscgbf8pmmhp9&st=aq94torh&dl=0). If you prefer swin-unetr, I will soon release it too.

Wow, your response speed is impressive! Thank you for your valuable advice. I plan to pre-train a model on a large-scale public pneumonia dataset, such as CC-CCII, and then fine-tune it on my own pneumonia classification task dataset. I will first try the weights and models you provided. Thank you again for your prompt reply.

**Comment by Luffy03** [comment]
Hi, the training logs and swinunetr checkpoints of CC-CCII (with pre-training) are updated in https://www.dropbox.com/scl/fo/svqaxxdpb75fo297ulljt/AMoWwRFKzTtxd4kVS2ZK03Q?rlkey=f1juzrxenx1qmq1sqq7nwaywg&st=39oqhkls&dl=0. And I have revised the CC-CCII training codes https://github.com/Luffy03/VoCo/tree/main/Finetune.

**Comment by Luffy03** [comment]
The former is right. For all finetuning tasks, we don't need the base crop operation, it is designed for pre-training.

**Comment by kare305** [comment]
> The former is right. For all finetuning tasks, we don't need the base crop operation, it is designed for pre-training.

Thank you for your answer, but if we follow the former approach, wouldn't it only focus on local image features, which can represent the entire CT image? Especially in downstream segmentation tasks, how is it operated?

**Comment by Luffy03** [comment]
Hi please read our codes first.
base crops for pretrain random crops for finetune

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
