### ISSUE TITLE
About abdominal segmentation

### ISSUE THREAD

**Issue by HYloong85** [Luffy03/VoCo#14]
The idea in your paper is impressive. I am particularly interested in your abdominal organ segmentation results and would like to use its weights to attempt pancreas segmentation on our dataset. Could you provide the model weights? If possible, I would greatly appreciate it.

**Comment by Luffy03** [comment]
Hi many thanks for your attention to our work!
Do you only want the pancreas segmentation models?

**Comment by Luffy03** [comment]
Here we have trained a model for pancreas and pancreas tumor segmentation https://www.dropbox.com/scl/fi/sfe4yo8v86h2g8coa8emr/model_pancreas.pt?rlkey=y07pmism66xa3r9sp0q6de0c0&st=26zrc79e&dl=0. This model outputs three channels (0: background, 1: pancreas, 2: pancreas tumor).

**Comment by HYloong85** [comment]
Thank you very much for your help. Wish you all the best.

**Comment by Luffy03** [comment]
Feel free to raise issues if you encounter any problems with this model.

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
