### ISSUE TITLE
About the memory cost

### ISSUE THREAD

**Issue by Devil-Ideal** [Luffy03/VoCo#23]
Hi ! How many GPUs are needed for model training, and what is the GPU memory of a single card ?

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work!
Currently, we use 8*H800 (80G) for 10K and 160K pre-training. Our 160k results will soon be available.

**Comment by Devil-Ideal** [comment]
> Hi, many thanks for your attention to our work! Currently, we use 8*H800 (80G) for 10K and 160K pre-training. Our 160k results will soon be available.

thank you

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
