### ISSUE TITLE
Supplementary materials

### ISSUE THREAD

**Issue by murong-xu** [Luffy03/VoCo#4]
Hi, thank you for this great work! Could you please let me know where I can find the supplementary materials? Having access to them would be very helpful to understand the paper. 

Many thanks!

**Comment by Luffy03** [comment]
Hi, many thanks for your kind attention to our work!
The appendix is submitted to the main conference. If you are interested in it, I will update it in Arxiv recently.

**Comment by murong-xu** [comment]
Thank you for your prompt reply! That would be wonderful, look forward to it :)

**Comment by Luffy03** [comment]
> Thank you for your prompt reply! That would be wonderful, look forward to it :)

Dear murong-xu, the version with appendix has been updated in arxiv('https://arxiv.org/abs/2402.17300'). You can check it if you are interested in.
But note that the current repo is using 10k data for pretraining while the arxiv manuscript describes the information of 1.6k pre-training, thus may be a little different.

**Comment by murong-xu** [comment]
Thank you very much for your update and kind notice :)
