### ISSUE TITLE
distributed training

### ISSUE THREAD

**Issue by gaoqiong123** [Luffy03/VoCo#5]
How to conduct distributed training? I'm using a single V100 GPU, and it's running out of memory. I want to use two V100 GPUs for training, but it seems like some parameters are missing?

**Comment by Luffy03** [comment]
Many thanks for your attention to our work first.
I have not yet tried training with multiple GPUs since one A100 GPU is already enough. Would you please try 'args.distributed = True' ('https://github.com/Luffy03/VoCo/blob/6f0e9d00ab66cedefca4e707d09e6c0afaf13364/voco_train.py#L174') if you want to use distributed training?

**Comment by gaoqiong123** [comment]
I used the program provided by you for pre-training, but it seems you did not provide an inference program. I tried to use Monai's swinunter for inference, but encountered the following error 
`Unexpected key(s) in state_dict: "swinViT.layers1c.0.layer.conv1.conv.weight", "swinViT.layers1c.0.layer.conv2.conv.weight", "swinViT.layers2c.0.layer.conv1.conv.weight", "swinViT.layers2c.0.layer.conv2.conv.weight", "swinViT.layers3c.0.layer.conv1.conv.weight", "swinViT.layers3c.0.layer.conv2.conv.weight", "swinViT.layers4c.0.layer.conv1.conv.weight", "swinViT.layers4c.0.layer.conv2.conv.weight"`

**Comment by Luffy03** [comment]
> I used the program provided by you for pre-training, but it seems you did not provide an inference program. I tried to use Monai's swinunter for inference, but encountered the following error `Unexpected key(s) in state_dict: "swinViT.layers1c.0.layer.conv1.conv.weight", "swinViT.layers1c.0.layer.conv2.conv.weight", "swinViT.layers2c.0.layer.conv1.conv.weight", "swinViT.layers2c.0.layer.conv2.conv.weight", "swinViT.layers3c.0.layer.conv1.conv.weight", "swinViT.layers3c.0.layer.conv2.conv.weight", "swinViT.layers4c.0.layer.conv1.conv.weight", "swinViT.layers4c.0.layer.conv2.conv.weight"`

Do you mean the inference of the following segmentation? I have provided the codes in '/Finetune/BTCV/trainer.py'.
If you want to load the checkpoint of SSL training, you can refer to 'https://github.com/Luffy03/VoCo/blob/6f0e9d00ab66cedefca4e707d09e6c0afaf13364/Finetune/BTCV/main.py#L170C13-L170C31'.
If you want to load the checkpoint of segmentation training, you should use 
![image](https://github.com/Luffy03/VoCo/assets/52514670/f741fc40-6852-41f0-8936-797f3c7e3ef5)

**Comment by gaoqiong123** [comment]
Could you please tell me your detailed training parameters? The pre-training batch size in the paper is 4, the sw batch size is 4, but this can not run in A100, will burst the display memory, and the number of num steps, can you tell me in detail



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Sun,Apr 21,2024 10:29 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





  
I used the program provided by you for pre-training, but it seems you did not provide an inference program. I tried to use Monai's swinunter for inference, but encountered the following error Unexpected key(s) in state_dict: "swinViT.layers1c.0.layer.conv1.conv.weight", "swinViT.layers1c.0.layer.conv2.conv.weight", "swinViT.layers2c.0.layer.conv1.conv.weight", "swinViT.layers2c.0.layer.conv2.conv.weight", "swinViT.layers3c.0.layer.conv1.conv.weight", "swinViT.layers3c.0.layer.conv2.conv.weight", "swinViT.layers4c.0.layer.conv1.conv.weight", "swinViT.layers4c.0.layer.conv2.conv.weight"
  
Do you mean the inference of the following segmentation? I have provided the codes in '/Finetune/BTCV/trainer.py'.
 If you want to load the checkpoint of SSL training, you can refer to 'https://github.com/Luffy03/VoCo/blob/6f0e9d00ab66cedefca4e707d09e6c0afaf13364/Finetune/BTCV/main.py#L170C13-L170C31'.
 If you want to load the checkpoint of segmentation training, you should use
 image.png (view on web)

**Comment by Luffy03** [comment]
Hi, the supplemental materials present the settings of our previous version. Please refer to the current settings (https://github.com/Luffy03/VoCo/blob/2cc3cf129095ca445eb191078b4682dde993160d/voco_train.py#L146). The number of steps is 250000 for 10k data (https://github.com/Luffy03/VoCo/blob/2cc3cf129095ca445eb191078b4682dde993160d/voco_train.py#L128).

**Comment by gaoqiong123** [comment]
Can you tell me the length of your training by the way? Thank you very much



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,Apr 25,2024 9:57 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





 
Hi, the supplemental materials present the settings of our previous version. Please refer to the current settings (https://github.com/Luffy03/VoCo/blob/2cc3cf129095ca445eb191078b4682dde993160d/voco_train.py#L146). The number of steps is 250000 for 10k data (https://github.com/Luffy03/VoCo/blob/2cc3cf129095ca445eb191078b4682dde993160d/voco_train.py#L128).

**Comment by Luffy03** [comment]
Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training.

**Comment by gaoqiong123** [comment]
I am sorry to bother you again ？I have downloaded the 10k dataset from hugging-face，However, it is different from what is written in the paper. I did not find the totalsegmentator in the hug face data set, but you seem to have used it. How did you handle the data set?thank you evrymuch&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,Apr 25,2024 10:08 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





 
Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training.

**Comment by gaoqiong123** [comment]
I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set?



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,Apr 25,2024 10:08 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





 
Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training.

**Comment by gaoqiong123** [comment]
could you tell me which version or give me a link ，thank you very much&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,Apr 25,2024 4:55 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





 
Thanks for pointing out! Sorry for my mistake. I will upload it soon or you can directly download it from the official website.

**Comment by Luffy03** [comment]
You can use google or github (https://github.com/wasserth/TotalSegmentator).

**Comment by Luffy03** [comment]
> I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it.

**Comment by gaoqiong123** [comment]
thank u very much, god bless u

**Comment by gaoqiong123** [comment]
Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters?



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Fri,Apr 26,2024 9:00 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





  
I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone
 …
 ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it.

**Comment by Luffy03** [comment]
> Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log?

**Comment by gaoqiong123** [comment]
Could you tell me the environment used by you?



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,May 9,2024 5:01 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





  
Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone
 …
 ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log?

**Comment by Luffy03** [comment]
> Could you tell me the environment used by you? 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,May 9,2024 5:01 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

I use torch 2.0.1+cu118. For your information, the details are updated in https://github.com/Luffy03/VoCo/blob/main/requirements.txt

**Comment by gaoqiong123** [comment]
I am sorry to bother you again and again ，Do you use the same BTCV data set for fine tuning and pre-training



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,May 9,2024 8:13 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





  
Could you tell me the environment used by you? 发自我的iPhone
 …
 ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 5:01 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
I use torch 2.0.1+cu118. For your information, the details are updated in https://github.com/Luffy03/VoCo/blob/main/requirements.txt

**Comment by Luffy03** [comment]
> I am sorry to bother you again and again ，Do you use the same BTCV data set for fine tuning and pre-training 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,May 9,2024 8:13 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Could you tell me the environment used by you? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 5:01 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; I use torch 2.0.1+cu118. For your information, the details are updated in https://github.com/Luffy03/VoCo/blob/main/requirements.txt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Yes, the same split. The val and test sets are not seen in pre-trainining.

**Comment by gaoqiong123** [comment]
What about fine-tuning? Is it trained on all the BTCV data?



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,May 9,2024 9:31 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





  
I am sorry to bother you again and again ，Do you use the same BTCV data set for fine tuning and pre-training 发自我的iPhone
 …
 ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 8:13 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Could you tell me the environment used by you? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 5:01 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; I use torch 2.0.1+cu118. For your information, the details are updated in https://github.com/Luffy03/VoCo/blob/main/requirements.txt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt;
  
Yes, the same split. The val and test sets are not seen in pre-trainining.

**Comment by Luffy03** [comment]
> What about fine-tuning? Is it trained on all the BTCV data? 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,May 9,2024 9:31 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again and again ，Do you use the same BTCV data set for fine tuning and pre-training 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 8:13 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Could you tell me the environment used by you? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,May 9,2024 5:01 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, State change @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Dear author,I am sorry to bother you again .I used the same data set as you. The graphics card I used was A800, the training parameters were the same as the parameters you published on github, and the environment I used was swinunter, where pytorch version was 2.1.0, but the inference result I got after fine tuning on btcv was only 0.79. Do you have any unpublished training parameters? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Fri,Apr 26,2024 9:00 PM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) I am sorry to bother you again,I have downloaded the 10k dataset from hugging face,However, it is different from what is written in the paper. I did not find the totalsegmentator in the hugging face data set, but you seem to have used it. How did you handle the data set? 发自我的iPhone … ------------------ Original ------------------ From: Linshan @.&gt; Date: Thu,Apr 25,2024 10:08 AM To: Luffy03/VoCo @.&gt; Cc: gaoqiong123 @.&gt;, Author @.&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5) Do you mean the training period? If you have pre-cached all 10k data and with powerful CPUs, it will take about two weeks for training. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, the totalsegmentator dataset has been uploaded to the huggingface. You can check it if you still need it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; It weired since without pre-training the accuracy can already surpass 0.8 with swinunetrv2. Would you please provide more details or the training log? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; I use torch 2.0.1+cu118. For your information, the details are updated in https://github.com/Luffy03/VoCo/blob/main/requirements.txt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; Yes, the same split. The val and test sets are not seen in pre-trainining. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Finetuning and pretraining use the same split.

**Comment by gaoqiong123** [comment]
I have one last question ，In your paper, you write about reasoning on BTCV data sets. Is it reasoning on all BTCV data sets?Thank u veryyyyyyy much&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,May 9,2024 9:49 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)

**Comment by Luffy03** [comment]
> I have one last question ，In your paper, you write about reasoning on BTCV data sets. Is it reasoning on all BTCV data sets?Thank u veryyyyyyy much&nbsp; 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,May 9,2024 9:49 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)

What do you mean reasoning?

**Comment by gaoqiong123** [comment]
I am sorry, it’s inference&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Thu,May 9,2024 10:09 PM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)

**Comment by Luffy03** [comment]
> I am sorry, it’s inference&nbsp; 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Linshan ***@***.***&gt; Date: Thu,May 9,2024 10:09 PM To: Luffy03/VoCo ***@***.***&gt; Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)

For inference, you can validate on the val set. It is more appropriate to submit the test results to the test leaderboard. However, the btcv leaderboard has not been updated for a long time. Thus, if you want to test on public leaderboard, I recommend you to verify the performance on Amos and Flare. For your information, I have updated the validation codes and the implementation on Amos and Flare.

**Comment by gaoqiong123** [comment]
Sorry for the lack of clarity, but what I want to ask is whether the score you get after pre-training on the btcv data set comes from the final &nbsp;accuracy of the fine-tuning or the inference on the btcv data set.Thank you very much&nbsp;

发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Fri,May 10,2024 9:48 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)

**Comment by Luffy03** [comment]
The final accuracy of fine-tuning. You can save the final checkpoint for inference (using val.py), and the results will be the same.

**Comment by gaoqiong123** [comment]
Hi,I noticed one thing, in the pre-training, Btcv.JSON in the jsons folder used 40 pictures to train, but in the fine-tuning, the btcv dataset you used was Dataset 0.json, is it the same?



发自我的iPhone


------------------ Original ------------------
From: Linshan ***@***.***&gt;
Date: Fri,May 10,2024 9:56 AM
To: Luffy03/VoCo ***@***.***&gt;
Cc: gaoqiong123 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [Luffy03/VoCo] distributed training (Issue #5)





 
The final accuracy of fine-tuning. You can save the final checkpoint for inference (using val.py), and the results will be the same.

**Comment by Luffy03** [comment]
Thanks for pointing out. There may be some mistakes with the uploaded json files. I will check it soon. You can directly use dataset_0.json file.

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
