### ISSUE TITLE
image classification

### ISSUE THREAD

**Issue by Zsilence-Jason** [Luffy03/VoCo#6]
Hi, thank you for this great work! How can I use the pre-trained model for image classification, such as the CC-CCII classification task mentioned in the paper?
Many thanks!

**Comment by Luffy03** [comment]
Many thanks for your attention to our work!
The implementation for CC-CCII classification has been uploaded. You need to edit the data_path of the CC-CCII dataset. I am not sure whether you have downloaded the dataset. If you have any problems with it, please feel free to raise them here.

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
