### ISSUE TITLE
Add Paper info for Prepare Dataset

### ISSUE THREAD

**Issue by Foursheeps** [Luffy03/VoCo#8]
Tiis  is very outstanding work! I am very interested in the pre training dataset collected. So what are the references corresponding to this image?, How to find this paper?
![10k](https://github.com/Luffy03/VoCo/assets/86510324/ee659528-1b31-4bcc-83f8-8dd92252d952)

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work!
This table is from the extention paper of our work, which is still in preparation. And a 100k version is comming soon, we will release them as soon as possible.

**Comment by Luffy03** [comment]
Dear researchers, our work is now available at [**Large-Scale-Medical**](https://github.com/Luffy03/Large-Scale-Medical), if you are still interested in this topic. Thank you very much for your attention to our work, it does encourage me a lot!
